CREATE TABLE PET
(
    PET_ID    BIGSERIAL NOT NULL PRIMARY KEY,
    PET_TYPE  VARCHAR(128) NOT NULL,
    NAME      VARCHAR(128) NOT NULL,
    OWNER_ID BIGINT NOT NULL,
    KEEPER_ID BIGINT NOT NULL,
    CONSTRAINT OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES APPLICATION_USER(APPLICATION_USER_ID),
    CONSTRAINT KEEPER_ID FOREIGN KEY (KEEPER_ID) REFERENCES APPLICATION_USER(APPLICATION_USER_ID),

);
