CREATE TABLE APPLICATION_USER
(
    APPLICATION_USER_ID        BIGSERIAL NOT NULL PRIMARY KEY,
    USERNAME                   VARCHAR(128) NOT NULL,
    PASSWORD                   VARCHAR(128) NOT NULL,
    EMAIL                      VARCHAR(128) NOT NULL,
    FIRST_NAME                 VARCHAR(128) NOT NULL,
    LAST_NAME                  VARCHAR(128) NOT NULL,
    NUMBER                     VARCHAR(128) NOT NULL,
    APPLICATION_ROLE           VARCHAR(128) NOT NULL,
    IS_ACCOUNT_NON_EXPIRED     NUMBER(1) NOT NULL,
    IS_ACCOUNT_NON_LOCKER      NUMBER(1) NOT NULL,
    IS_CREDENTIALS_NON_EXPIRED NUMBER(1) NOT NULL,
    IS_ENABLED                 NUMBER(1) NOT NULL
);
